version: '3'

services:

  api:
    build:
      context: api
    command: >
            /bin/bash -c "
                until echo > /dev/tcp/postgres/5432; do sleep 1; done
                python manage.py migrate citations
                python manage.py migrate
                python manage.py runserver 0.0.0.0:8000
            "
    volumes:
      - ./api/app:/srv/app
    depends_on:
      - postgres

  api-nginx:
    image: nginx:1.13.12-alpine
    ports:
      - '8000:80'
    volumes:
      - ./api/.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  client:
    build:
      context: client
    volumes:
        - ./client:/srv/app
        - /srv/app/build
        - /srv/app/node_modules
    ports:
      - '8080:3000'
      - '8081:3001'

  postgres:
    image: postgres:9.6.8-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=rootpassword
      - POSTGRES_DB=default
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
  postgres:
